FROM python:3.11-slim

RUN pip install --no-cache-dir flask gunicorn

WORKDIR /app
COPY . .

ENV PYTHONPATH=/app
ENV FLASK_APP=GUI/app.py

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--threads", "4", "GUI.app:app"]
